// Contract ABIs - Imported directly from JSON files generated by Hardhat
// This ensures we always use the latest deployed contract ABIs

import VitalChainCoreArtifact from "./VitalChainCore.json" assert { type: "json" };
import PatientRecordsArtifact from "./PatientRecords.json" assert { type: "json" };
import AccessControlManagerArtifact from "./AccessControlManager.json" assert { type: "json" };
import AuditLogArtifact from "./AuditLog.json" assert { type: "json" };
import EmergencyAccessArtifact from "./EmergencyAccess.json" assert { type: "json" };
import InsuranceClaimsArtifact from "./InsuranceClaims.json" assert { type: "json" };

export const VitalChainCoreABI = VitalChainCoreArtifact.abi as any;
export const PatientRecordsABI = PatientRecordsArtifact.abi as any;
export const AccessControlManagerABI = AccessControlManagerArtifact.abi as any;
export const AuditLogABI = AuditLogArtifact.abi as any;
export const EmergencyAccessABI = EmergencyAccessArtifact.abi as any;
export const InsuranceClaimsABI = InsuranceClaimsArtifact.abi as any;
